name = "cloudflare-plugin"
main = "src/index.ts"
compatibility_date = "2022-08-29"
kv_namespaces = [
    { binding = "submit_plugin", preview_id = "fbf7a566102740ef9a2e588c19b527fa", id = "fbf7a566102740ef9a2e588c19b527fa" }
]